### ISSUE TITLE
[ENHANCEMENT] Refactor Setup class into one single file

### ISSUE THREAD

**Issue by hikager** [hikager/docker4mongodb-dam2-m6-uf3#17]
## Description
Make the Setup class into one single file and change the script to execute to `run.py`

# TODOs
- [x] Refactor setup class 
- [x] Add new file to execute the script
- [x] Update README.md
